<#
.SYNOPSIS
  Starts a private TS server on this Windows PC in Docker, reachable only through Tailscale.

.DESCRIPTION
  1. Generates secrets (once) and a .env file.
  2. Builds and starts the server with docker-compose.tailscale.yml, so the port is bound to
     127.0.0.1 and not visible from the LAN or the internet.
  3. Prints the remaining Tailscale step.

  Run from the repository root:
    powershell -ExecutionPolicy Bypass -File scripts\local-server.ps1 -PublicUrl https://mypc.tailXXXX.ts.net -Admin alijon

  REGISTRATION_MODE is set to "open" for testing only. Switch it to invite_only in .env and run
  `docker compose -f docker-compose.yml -f docker-compose.tailscale.yml up -d` once the accounts exist.
#>
param(
    [Parameter(Mandatory = $true)][string]$PublicUrl,
    [string]$Admin = ""
)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)

if ($PublicUrl -notmatch '^https://[a-z0-9.-]+$') {
    throw "PublicUrl must look like https://name.tailnet.ts.net (https, no path, no trailing slash)."
}
docker version --format '{{.Server.Version}}' | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Docker is not running. Start Docker Desktop first." }

$utf8 = New-Object System.Text.UTF8Encoding($false)
function New-Hex([int]$bytes) {
    $b = New-Object byte[] $bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($b)
    $rng.Dispose()
    -join ($b | ForEach-Object { $_.ToString("x2") })
}

New-Item -ItemType Directory -Force -Path secrets | Out-Null

if (-not (Test-Path secrets\jwt_private.pem)) {
    Write-Host "Generating JWT signing keys..."
    $dir = (Resolve-Path secrets).Path
    docker run --rm -v "${dir}:/s" alpine/openssl genpkey -algorithm Ed25519 -out /s/jwt_private.pem
    docker run --rm -v "${dir}:/s" alpine/openssl pkey -in /s/jwt_private.pem -pubout -out /s/jwt_public.pem
    if (-not (Test-Path secrets\jwt_public.pem)) { throw "Key generation failed." }
}
if (-not (Test-Path secrets\db_password)) {
    [IO.File]::WriteAllText((Join-Path (Get-Location) "secrets\db_password"), (New-Hex 24), $utf8)
}
if (-not (Test-Path secrets\totp_encryption_key)) {
    [IO.File]::WriteAllText((Join-Path (Get-Location) "secrets\totp_encryption_key"), (New-Hex 32), $utf8)
}

# The server runs as an unprivileged user inside its container. openssl creates the private key
# with mode 600 (root only), which the server then cannot read ("Permission denied"). Make the
# files readable for the container; they live in this folder on a single-user PC.
$secretsDir = (Resolve-Path secrets).Path
docker run --rm -v "${secretsDir}:/s" --entrypoint sh alpine/openssl -c "chmod 755 /s && chmod 644 /s/*"
if ($LASTEXITCODE -ne 0) { throw "Could not set permissions on the secrets folder." }

if (-not (Test-Path .env)) {
    $db = [IO.File]::ReadAllText((Join-Path (Get-Location) "secrets\db_password")).Trim()
    $totp = [IO.File]::ReadAllText((Join-Path (Get-Location) "secrets\totp_encryption_key")).Trim()
    $envText = @"
# Generated by scripts/local-server.ps1. Never commit this file.
DB_PASSWORD=$db
DATABASE_URL=postgres://ts:$db@postgres:5432/ts
JWT_PRIVATE_KEY_PATH=/run/secrets/jwt_private_key
JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public_key
TOTP_ENCRYPTION_KEY=$totp
RUST_LOG=ts_server=info,tower_http=info
FILE_STORAGE_PATH=/app/data/files
MAX_FILE_SIZE_MB=100
LISTEN_ADDR=0.0.0.0:8080
PUBLIC_URL=$PublicUrl
ICE_SERVERS=[]
# Small private instance: everyone can find everyone by name.
SEARCH_ALL_USERS=true
# TESTING ONLY: anyone who can reach the server may register. Change to invite_only afterwards.
REGISTRATION_MODE=open
ADMIN_USERNAME=$Admin
"@
    [IO.File]::WriteAllText((Join-Path (Get-Location) ".env"), $envText, $utf8)
    Write-Host "Created .env"
} else {
    Write-Host ".env already exists, keeping it."
}

Write-Host "Building and starting TS (the first build takes 15-30 minutes)..."
docker compose -f docker-compose.yml -f docker-compose.tailscale.yml up -d --build
if ($LASTEXITCODE -ne 0) { throw "docker compose failed." }

Write-Host ""
Write-Host "Waiting for the server to become healthy..."
$ok = $false
for ($i = 0; $i -lt 30; $i++) {
    try {
        $r = Invoke-WebRequest -UseBasicParsing -Uri http://127.0.0.1:8080/api/health -TimeoutSec 3
        if ($r.StatusCode -eq 200) { $ok = $true; break }
    } catch { }
    Start-Sleep -Seconds 4
}
if (-not $ok) {
    Write-Host "Server did not answer. Logs:" -ForegroundColor Yellow
    docker compose -f docker-compose.yml -f docker-compose.tailscale.yml logs --tail 50 ts
    exit 1
}
Write-Host "Server is up on 127.0.0.1:8080 (this PC only)." -ForegroundColor Green
Write-Host ""
Write-Host "Last step, publish it inside your tailnet:"
Write-Host "  tailscale serve --bg --https=443 http://127.0.0.1:8080"
Write-Host "  tailscale serve status"
Write-Host "Then open $PublicUrl in a browser on a device that is in your tailnet."
